# Generated by Django 2.0.6 on 2018-08-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180804_2256'),
        ('app', '0003_auto_20180806_1728'),
    ]

    operations = [
    ]
